language: node_js
node_js:
- '6'
script:
- npm run build
- npm test
deploy:
  provider: releases
  api_key:
    secure: D0uBx5Q4e9R3A74u2e54TJz1jMeHuj/mB2bKNsA52ghKUCunZXArcO0c5GSivngeTQjP86dxyICN1R+PQ5n3pAIhCXZD47vD65iOAnTDPRGQvdVcgzV3GzWG2A1oUpFmxrK3PucwVIhbIkIqZ29A+xgsaT5smDQBCOlTBoswiZ41dNaSqgU4oKasXUPJEY/mGS2IoFYluvBBiFX6Oskk45wkBMjPssyxWtE/1YJlHRGuWQrg4N0vkL8F232pG/64DadxOESfnPRyHyTlSt6ij81t2GPUi0vEyd/jTH9Ear9AudU6DoCz5EN4OmPPAX4HYVoff9WGwF1FlE38j0O9o78A6RrfGVTP2SpRykxKZPpkxnL1TdqNvLXjpIh6+MhzjNiemRrLoJjbmFVYHOj8auMgSbayED1P7om2xQywi+p5uXN6S9tsgyF27sowF0b9QMJQCf4aZQNUGphdfJJDm/MYNwxRcqydX1y6F1CTdOSah0gvPFQGPotO3v4VcDDTNKojDk52rB6pijdJFdYTz/GVKJvXLFESDJjeNnl72/ZLL+oI4SMpGSl/9QAI37r9HS2eOG0oTaTVeckr5VDK6uqs9Y7LkANFQzo9hBjD0e76WXfgTUhzASd1hAK3PpY8pWDKhvS+jB4uU2kaNhEUxUUgxgALd8nuwPGFXX5lGD4=
  file: dist/browser/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: imdreamrunner/js-id-number
    tags: true
